#!/usr/bin/env node
// bmad-generated:eb17b090
// BMAD Swarm - PreToolUse gate on TeamCreate
// Generated by bmad-swarm - do not edit manually
//
// Parses the JSONL transcript and requires a fenced bmad-assembly block with
// the required keys to appear in the last N=5 assistant message.ids. Accepts
// both 'text' and 'thinking' content blocks. Widening the search from the
// single last message.id to the last 5 message.ids covers streaming splits,
// retries after transient failures, and the common 'plan in message → tool_use
// in next message' pattern. Fails open when the transcript is missing or
// unreadable. This is a shape check, not an authorization boundary.
//
// GATE-1 (2.0.2): raw-transcript-scan fallback. When the structured content-
// block walk does not surface the fence — observed when an assistant message
// starts with only a fenced bmad-assembly block and the transcript JSON
// encodes the content in a shape the typed walk misses — a secondary pass
// scans the raw transcript text for the fence. Both passes enforce the same
// 5-key requirement; only denies if NEITHER finds a valid block.

const fs = require('fs');
let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (c) => { input += c; });
process.stdin.on('end', () => {
  let event;
  try { event = JSON.parse(input); } catch { process.exit(0); }
  const transcriptPath = event.transcript_path;
  if (!transcriptPath || !fs.existsSync(transcriptPath)) { process.exit(0); }
  let raw;
  try { raw = fs.readFileSync(transcriptPath, 'utf8'); } catch { process.exit(0); }

  const entries = raw.split(/\r?\n/).filter(Boolean)
    .map(l => { try { return JSON.parse(l); } catch { return null; } })
    .filter(e => e && e.type === 'assistant' && e.message);
  const REQUIRED_KEYS = ['entry_point', 'complexity', 'autonomy', 'team', 'rationale'];
  const FENCE_RE = /```bmad-assembly\s*\n([\s\S]*?)\n```/;
  function deny(missing) {
    process.stdout.write(JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: 'Blocked: produce a bmad-assembly block (with keys: ' + REQUIRED_KEYS.join(', ') + ') in your message BEFORE calling TeamCreate. Missing: ' + missing.join(', '),
      },
    }));
  }
  function missingKeys(block) {
    if (!block) return REQUIRED_KEYS.slice();
    return REQUIRED_KEYS.filter(k => !new RegExp('^\\s*' + k + ':', 'm').test(block));
  }
  if (entries.length === 0) { deny(REQUIRED_KEYS); process.exit(0); }

  // Pass 1: structured content-block walk over last N=5 distinct assistant
  // message.ids, accepting both 'text' and 'thinking' blocks.
  const N = 5;
  const recentIds = new Set();
  for (let i = entries.length - 1; i >= 0 && recentIds.size < N; i--) {
    recentIds.add(entries[i].message.id);
  }
  const texts = [];
  for (const e of entries) {
    if (!recentIds.has(e.message.id)) continue;
    const content = Array.isArray(e.message.content) ? e.message.content : [];
    for (const b of content) {
      if (!b) continue;
      if (b.type === 'text' && b.text) texts.push(b.text);
      else if (b.type === 'thinking' && b.thinking) texts.push(b.thinking);
    }
  }
  const structuredText = texts.join('\n');
  const structuredMatch = structuredText.match(FENCE_RE);
  const structuredMissing = missingKeys(structuredMatch ? structuredMatch[1] : null);
  if (structuredMissing.length === 0) { process.exit(0); }

  // Pass 2: raw-transcript-scan fallback. GATE-1 observed that some message
  // shapes don't surface the fence through the typed-block walk; scanning the
  // raw JSON directly catches those. Scope the raw scan to only the raw JSONL
  // lines whose parsed assistant entries belong to the same recent N message
  // ids the structured walk used — preserves the "plan BEFORE create"
  // recency invariant while recovering from walk-misses. The raw JSONL
  // encodes real newlines as the two-char sequence \n so we un-escape those
  // before matching so a fence that exists only inside a JSON-stringified
  // value still triggers a pass. Also cap the scanned region at ~50KB as a
  // belt-and-braces guard against pathological transcripts.
  const RAW_TAIL_BYTES = 50 * 1024;
  const rawLines = raw.split(/\r?\n/);
  const recentRawLines = [];
  for (const line of rawLines) {
    if (!line) continue;
    let parsed;
    try { parsed = JSON.parse(line); } catch { continue; }
    if (parsed && parsed.type === 'assistant' && parsed.message && recentIds.has(parsed.message.id)) {
      recentRawLines.push(line);
    }
  }
  let rawScope = recentRawLines.join('\n');
  if (rawScope.length > RAW_TAIL_BYTES) {
    rawScope = rawScope.slice(rawScope.length - RAW_TAIL_BYTES);
  }
  const rawUnescaped = rawScope.replace(/\\n/g, '\n');
  const rawMatch = rawUnescaped.match(FENCE_RE);
  if (rawMatch) {
    const rawMissing = missingKeys(rawMatch[1]);
    if (rawMissing.length === 0) { process.exit(0); }
  }

  deny(structuredMissing);
  process.exit(0);
});
