import { existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { getProjectPaths } from '../utils/paths.js';
import { loadSwarmConfig, getAgentNames } from '../utils/config.js';
import { readFileSafe } from '../utils/fs-helpers.js';

export function registerDoctorCommand(program) {
  program
    .command('doctor')
    .description('Check project configuration health and report issues')
    .addHelpText('after', `
Examples:
  $ bmad-swarm doctor    Run all health checks
`)
    .action(async () => {
      try {
        await runDoctor();
      } catch (err) {
        console.error(`Error: ${err.message}`);
        process.exit(1);
      }
    });
}

async function runDoctor() {
  const projectRoot = process.cwd();
  const paths = getProjectPaths(projectRoot);
  let hasIssues = false;

  console.log('\nBMAD Swarm Health Check\n');

  // 1. swarm.yaml
  if (existsSync(paths.swarmYaml)) {
    try {
      const config = loadSwarmConfig(paths.swarmYaml);
      check(true, 'swarm.yaml exists and is valid');

      // 3. Agent files
      const enabledAgents = getAgentNames().filter(name => {
        const agentConfig = config.agents?.[name];
        return agentConfig?.enabled !== false;
      });
      let agentIssues = 0;
      for (const name of enabledAgents) {
        const agentPath = join(paths.agentsDir, `${name}.md`);
        if (!existsSync(agentPath)) {
          agentIssues++;
        }
      }
      if (agentIssues === 0) {
        check(true, `.claude/agents/ has all ${enabledAgents.length} enabled agents`);
      } else {
        check(false, `.claude/agents/ is missing ${agentIssues} agent file(s)`, 'Run `bmad-swarm update` to regenerate');
        hasIssues = true;
      }
    } catch (err) {
      check(false, `swarm.yaml has validation errors: ${err.message}`, 'Fix the errors in swarm.yaml');
      hasIssues = true;
    }
  } else {
    check(false, 'swarm.yaml not found', 'Run `bmad-swarm init` to create');
    hasIssues = true;
  }

  // 4. CLAUDE.md
  if (existsSync(paths.claudeMd)) {
    const content = readFileSafe(paths.claudeMd);
    if (content && /<!-- bmad-generated:[a-f0-9]+/.test(content)) {
      check(true, 'CLAUDE.md exists and was generated by bmad-swarm');
    } else {
      check(false, 'CLAUDE.md exists but may not be generated by bmad-swarm', 'Run `bmad-swarm update` to regenerate');
      hasIssues = true;
    }
  } else {
    check(false, 'CLAUDE.md not found', 'Run `bmad-swarm update` to generate');
    hasIssues = true;
  }

  // 5. Hooks
  if (existsSync(paths.hooksDir)) {
    const hooks = readdirSync(paths.hooksDir).filter(f => f.endsWith('.js') || f.endsWith('.cjs') || f.endsWith('.sh'));
    if (hooks.length > 0) {
      check(true, `.claude/hooks/ has ${hooks.length} hook(s)`);
    } else {
      check(false, '.claude/hooks/ exists but has no hooks', 'Run `bmad-swarm update` to regenerate');
      hasIssues = true;
    }
  } else {
    check(false, '.claude/hooks/ not found', 'Run `bmad-swarm update` to generate');
    hasIssues = true;
  }

  // 6. settings.json
  if (existsSync(paths.settingsJson)) {
    check(true, '.claude/settings.json exists');
  } else {
    check(false, '.claude/settings.json not found', 'Run `bmad-swarm update` to generate');
    hasIssues = true;
  }

  // 7. project.yaml
  if (existsSync(paths.projectYaml)) {
    check(true, 'project.yaml exists');
  } else {
    check(false, 'project.yaml not found', 'Run `bmad-swarm init` to create');
    hasIssues = true;
  }

  // 8. Artifact directories
  const artifactDirs = ['exploration', 'planning', 'design', 'implementation', 'reviews', 'context'];
  let missingDirs = 0;
  for (const dir of artifactDirs) {
    if (!existsSync(join(paths.artifactsDir, dir))) {
      missingDirs++;
    }
  }
  if (missingDirs === 0) {
    check(true, 'All artifact directories exist');
  } else {
    check(false, `Missing ${missingDirs} artifact director${missingDirs > 1 ? 'ies' : 'y'}`, 'Run `bmad-swarm init` to create');
    hasIssues = true;
  }

  // 9. Orphaned overrides
  if (existsSync(paths.overridesAgentsDir)) {
    const overrides = readdirSync(paths.overridesAgentsDir).filter(f => f.endsWith('.md'));
    const orphaned = overrides.filter(f => !getAgentNames().includes(f.replace('.md', '')));
    if (orphaned.length === 0) {
      check(true, 'No orphaned override files');
    } else {
      check(false, `Orphaned override files: ${orphaned.join(', ')}`, 'Remove unused override files from overrides/agents/');
      hasIssues = true;
    }
  }

  console.log('');
  if (hasIssues) {
    console.log('Issues found. See suggestions above.');
    process.exit(1);
  } else {
    console.log('All checks passed!');
  }
}

function check(pass, message, fix) {
  const icon = pass ? '\u2713' : '\u2717';
  console.log(`  ${icon} ${message}`);
  if (!pass && fix) {
    console.log(`    Fix: ${fix}`);
  }
}
